# Generated by Django 4.2.16 on 2024-11-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task_table",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=25, null=True)),
                ("task_description", models.CharField(max_length=200, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_task", models.BooleanField(default=False)),
            ],
        ),
    ]
