# Generated by Django 4.2.16 on 2024-11-13 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task_table",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
